### Importing the needed libraries

In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
import random
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler #you can use minmax scaler too
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import xgboost as xgb
from imblearn.ensemble import BalancedBaggingClassifier
#Import other necessary model libraries, for this example, using Logistic Regression

### Importing the dataset

In [116]:
train_data = pd.read_csv(r"../Data/Preprocessed-Datasets/train-data-encoded.csv", header = 0)
test_data = pd.read_csv(r"../Data/Preprocessed-Datasets/test-data-encoded.csv", header = 0)
validation_data = pd.read_csv(r"../Data/Preprocessed-Datasets/validation-data-encoded.csv", header = 0)

In [117]:
train_data=train_data.drop(['Reservation-id'], axis = 1)
validation_data=validation_data.drop(['Reservation-id'], axis = 1)
test_data_id = test_data['Reservation-id']
test_data=test_data.drop(['Reservation-id'], axis = 1)

In [118]:
train_data_ori = train_data
validation_data_ori = validation_data
test_data_ori = test_data

In [119]:
train_data.head()

Age  Adults  Children  Babies Reservation_Status  Discount_Rate  Room_Rate  \
0   40       2         2       0           Check-In             10        218   
1   49       3         3       0           Check-In              0        185   
2   42       3         3       0           Check-In              0        119   
3   25       4         3       0           Check-In              5        144   
4   62       1         1       0           Check-In             10        242   

   Expected_stay_days  Reservation_gap  Gender_F  ...  \
0                   1               41         1  ...   
1                   1               36         1  ...   
2                   4                3         1  ...   
3                   1               12         0  ...   
4                   1               13         1  ...   

   Deposit_type_No Deposit  Deposit_type_Non-Refundable  \
0                        1                            0   
1                        0                            0   
2                        1                            0   
3                        0                            0   
4                        1                            0   

   Deposit_type_Refundable  Booking_channel_Agent  Booking_channel_Direct  \
0                        0                      0                       0   
1                        1                      0                       0   
2                        0                      0                       0   
3                        1                      1                       0   
4                        0                      0                       1   

   Booking_channel_Online  Required_Car_Parking_No  Required_Car_Parking_Yes  \
0                       1                        0                         1   
1                       1                        0                         1   
2                       1                        0                         1   
3                       0                        0                         1   
4                       0                        1                         0   

   Use_Promotion_No  Use_Promotion_Yes  
0                 0                  1  
1                 1                  0  
2                 1                  0  
3                 0                  1  
4                 0                  1  

[5 rows x 47 columns]

In [120]:
validation_data.head()

Age  Adults  Children  Babies Reservation_Status  Discount_Rate  Room_Rate  \
0   56       2         2       0            No-Show             15        192   
1   60       2         2       0           Canceled              0        187   
2   58       3         1       0           Canceled             10        227   
3   23       1         2       0           Check-In             25        189   
4   47       1         1       0           Check-In             10        218   

   Expected_stay_days  Reservation_gap  Gender_F  ...  \
0                   2              195         0  ...   
1                   4              175         0  ...   
2                   1              193         1  ...   
3                   2              103         1  ...   
4                   1               92         1  ...   

   Deposit_type_No Deposit  Deposit_type_Non-Refundable  \
0                        1                            0   
1                        1                            0   
2                        1                            0   
3                        0                            0   
4                        1                            0   

   Deposit_type_Refundable  Booking_channel_Agent  Booking_channel_Direct  \
0                        0                      1                       0   
1                        0                      0                       0   
2                        0                      0                       1   
3                        1                      0                       1   
4                        0                      0                       0   

   Booking_channel_Online  Required_Car_Parking_No  Required_Car_Parking_Yes  \
0                       0                        1                         0   
1                       1                        0                         1   
2                       0                        1                         0   
3                       0                        1                         0   
4                       1                        0                         1   

   Use_Promotion_No  Use_Promotion_Yes  
0                 0                  1  
1                 1                  0  
2                 0                  1  
3                 0                  1  
4                 0                  1  

[5 rows x 47 columns]

In [121]:
validation_data.head()

Age  Adults  Children  Babies Reservation_Status  Discount_Rate  Room_Rate  \
0   56       2         2       0            No-Show             15        192   
1   60       2         2       0           Canceled              0        187   
2   58       3         1       0           Canceled             10        227   
3   23       1         2       0           Check-In             25        189   
4   47       1         1       0           Check-In             10        218   

   Expected_stay_days  Reservation_gap  Gender_F  ...  \
0                   2              195         0  ...   
1                   4              175         0  ...   
2                   1              193         1  ...   
3                   2              103         1  ...   
4                   1               92         1  ...   

   Deposit_type_No Deposit  Deposit_type_Non-Refundable  \
0                        1                            0   
1                        1                            0   
2                        1                            0   
3                        0                            0   
4                        1                            0   

   Deposit_type_Refundable  Booking_channel_Agent  Booking_channel_Direct  \
0                        0                      1                       0   
1                        0                      0                       0   
2                        0                      0                       1   
3                        1                      0                       1   
4                        0                      0                       0   

   Booking_channel_Online  Required_Car_Parking_No  Required_Car_Parking_Yes  \
0                       0                        1                         0   
1                       1                        0                         1   
2                       0                        1                         0   
3                       0                        1                         0   
4                       1                        0                         1   

   Use_Promotion_No  Use_Promotion_Yes  
0                 0                  1  
1                 1                  0  
2                 0                  1  
3                 0                  1  
4                 0                  1  

[5 rows x 47 columns]

q1 = train_data.quantile(0.25)
q3 = train_data.quantile(0.75)
iqr = q2-q1
train_data = train_data[~((train_data<(q1-1.5*iqr))|(train_data>(q3+1.5*iqr))).any(axis=1)]
train_data.shape

### Seperating the columns of categorical and quantitative data

In [122]:
train_data['Fam_memb'] = train_data['Adults'] + train_data['Children'] + train_data['Babies']
#train_data.drop(['Adults','Children','Babies'], inplace= True)

In [123]:
train_data.drop(['Adults','Children','Babies'],axis=1, inplace= True)
train_data.head()

Age Reservation_Status  Discount_Rate  Room_Rate  Expected_stay_days  \
0   40           Check-In             10        218                   1   
1   49           Check-In              0        185                   1   
2   42           Check-In              0        119                   4   
3   25           Check-In              5        144                   1   
4   62           Check-In             10        242                   1   

   Reservation_gap  Gender_F  Gender_M  Ethnicity_African American  \
0               41         1         0                           0   
1               36         1         0                           0   
2                3         1         0                           0   
3               12         0         1                           1   
4               13         1         0                           0   

   Ethnicity_Asian American  ...  Deposit_type_Non-Refundable  \
0                         0  ...                            0   
1                         0  ...                            0   
2                         0  ...                            0   
3                         0  ...                            0   
4                         0  ...                            0   

   Deposit_type_Refundable  Booking_channel_Agent  Booking_channel_Direct  \
0                        0                      0                       0   
1                        1                      0                       0   
2                        0                      0                       0   
3                        1                      1                       0   
4                        0                      0                       1   

   Booking_channel_Online  Required_Car_Parking_No  Required_Car_Parking_Yes  \
0                       1                        0                         1   
1                       1                        0                         1   
2                       1                        0                         1   
3                       0                        0                         1   
4                       0                        1                         0   

   Use_Promotion_No  Use_Promotion_Yes  Fam_memb  
0                 0                  1         4  
1                 1                  0         6  
2                 1                  0         6  
3                 0                  1         7  
4                 0                  1         2  

[5 rows x 45 columns]

In [124]:
validation_data['Fam_memb'] = validation_data['Adults'] + validation_data['Children'] + validation_data['Babies']
validation_data.drop(['Adults','Children','Babies'], axis=1, inplace= True)

In [125]:
test_data['Fam_memb'] = test_data['Adults'] + test_data['Children'] + test_data['Babies']
test_data.drop(['Adults','Children','Babies'],axis=1, inplace= True)

In [126]:
#data_quan_cols = ['Age','Discount_Rate', 'Room_Rate','Expected_stay_days', 'Reservation_gap', 'Adults', 'Children','Babies']
data_quan_cols = ['Age','Discount_Rate', 'Room_Rate','Expected_stay_days', 
                        'Reservation_gap', 'Fam_memb']

In [127]:
data_cat_cols = ['Gender', 'Ethnicity', 'Educational_Level', 'Income', 'Country_region',
                 'Hotel_Type', 'Meal_Type', 'Visted_Previously',
                 'Previous_Cancellations', 'Deposit_type', 'Booking_channel',
                 'Required_Car_Parking', 'Use_Promotion']

### Scaling the quantitative variables

In [128]:
train_data_quan = train_data[data_quan_cols]
validation_data_quan = validation_data[data_quan_cols]
test_data_quan = test_data[data_quan_cols]

In [129]:
from sklearn.preprocessing import MinMaxScaler 
sc = StandardScaler()
#sc = MinMaxScaler()

In [130]:
train_data_quan_scaled = sc.fit_transform(train_data_quan)
validation_data_quan_scaled = sc.transform(validation_data_quan)
test_data_quan_scaled = sc.transform(test_data_quan)

In [131]:
train_data_quan_scaled

array([[-0.25991554, -0.22266812,  0.97691768, -0.84878606, -0.88293639,
        -0.28704082],
       [ 0.32820944, -1.11506055,  0.22480302, -0.84878606, -0.94700001,
         1.05115289],
       [-0.1292211 , -1.11506055, -1.27942629,  2.1963239 , -1.36981989,
         1.05115289],
       ...,
       [ 0.32820944, -0.66886434,  0.61225603, -0.84878606, -1.29294354,
        -0.28704082],
       [ 1.37376495,  0.66972431, -0.41335487, -0.84878606, -0.15261114,
         0.38205603],
       [ 0.26286222, -1.11506055,  0.79458685, -0.84878606, -0.57543102,
        -0.28704082]])

In [132]:
type(train_data_quan_scaled)

numpy.ndarray

### Separating the categorical variables

In [133]:
cols_to_drop = data_quan_cols.copy()
cols_to_drop.append("Reservation_Status")
cols_to_drop

['Age',
 'Discount_Rate',
 'Room_Rate',
 'Expected_stay_days',
 'Reservation_gap',
 'Fam_memb',
 'Reservation_Status']

In [134]:
print(cols_to_drop)

['Age', 'Discount_Rate', 'Room_Rate', 'Expected_stay_days', 'Reservation_gap', 'Fam_memb', 'Reservation_Status']


In [135]:
train_data_cat = train_data.drop(cols_to_drop, axis=1)
validation_data_cat = validation_data.drop(cols_to_drop, axis=1)
test_data_cat = test_data.drop(data_quan_cols, axis=1)
train_data_cat.head()

Gender_F  Gender_M  Ethnicity_African American  Ethnicity_Asian American  \
0         1         0                           0                         0   
1         1         0                           0                         0   
2         1         0                           0                         0   
3         0         1                           1                         0   
4         1         0                           0                         0   

   Ethnicity_Latino  Ethnicity_caucasian  Educational_Level_College  \
0                 1                    0                          0   
1                 1                    0                          0   
2                 0                    1                          0   
3                 0                    0                          1   
4                 1                    0                          0   

   Educational_Level_Grad  Educational_Level_High-School  \
0                       1                              0   
1                       0                              0   
2                       1                              0   
3                       0                              0   
4                       0                              1   

   Educational_Level_Mid-School  ...  Deposit_type_No Deposit  \
0                             0  ...                        1   
1                             1  ...                        0   
2                             0  ...                        1   
3                             0  ...                        0   
4                             0  ...                        1   

   Deposit_type_Non-Refundable  Deposit_type_Refundable  \
0                            0                        0   
1                            0                        1   
2                            0                        0   
3                            0                        1   
4                            0                        0   

   Booking_channel_Agent  Booking_channel_Direct  Booking_channel_Online  \
0                      0                       0                       1   
1                      0                       0                       1   
2                      0                       0                       1   
3                      1                       0                       0   
4                      0                       1                       0   

   Required_Car_Parking_No  Required_Car_Parking_Yes  Use_Promotion_No  \
0                        0                         1                 0   
1                        0                         1                 1   
2                        0                         1                 1   
3                        0                         1                 0   
4                        1                         0                 0   

   Use_Promotion_Yes  
0                  1  
1                  0  
2                  0  
3                  1  
4                  1  

[5 rows x 38 columns]

In [136]:
train_data_cat_array = train_data_cat.to_numpy()
validation_data_cat_array = validation_data_cat.to_numpy()
test_data_cat_array = test_data_cat.to_numpy()
train_data_cat_array.shape

(27499, 38)

### Joining the pre-processed data

In [137]:
train_data_processed = np.concatenate((train_data_quan_scaled, train_data_cat_array), axis = 1)
validation_data_processed = np.concatenate((validation_data_quan_scaled, validation_data_cat_array), axis = 1)
test_data_processed = np.concatenate((test_data_quan_scaled, test_data_cat_array), axis = 1)

In [138]:
train_data_processed[0]

array([-0.25991554, -0.22266812,  0.97691768, -0.84878606, -0.88293639,
       -0.28704082,  1.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  1.        ,  0.        ,  1.        ])

In [139]:
test_data_quan_scaled.shape

(4318, 6)

In [140]:
test_data_cat_array.shape

(4318, 38)

In [141]:
validation_data_processed.shape

(2749, 44)

### Encoding the labels

In [142]:
train_y = train_data['Reservation_Status']
validation_y = validation_data['Reservation_Status']

In [143]:
le = preprocessing.LabelEncoder()

In [144]:
train_y = le.fit_transform(train_y)
validation_y = le.transform(validation_y)

In [145]:
validation_y.shape

(2749,)

In [146]:
le.classes_

array(['Canceled', 'Check-In', 'No-Show'], dtype=object)

### Oversampling and Undersampling

In [147]:
train_y_count = np.bincount(train_y)
train_y_count

array([ 4134, 21240,  2125], dtype=int64)

#### oversampling

from imblearn.over_sampling import SMOTE
#0: Cancelled, 1: Check--in , 2:No Show
#Oversampling
strategy = {0:4134*5, 1:21240, 2:2125*9}
smote = SMOTE(sampling_strategy=strategy, random_state = 0) 

X_smote, y_smote = smote.fit_resample(train_data_processed, train_y)
#print(Counter(y_train), Counter(y_smote))
unique_smote = np.bincount(y_smote)
unique_smote

### Borderline SMOTE
from imblearn.over_sampling import BorderlineSMOTE
strategy = {0:4134*5, 1:21240, 2:2125*9}
blsmote = BorderlineSMOTE(sampling_strategy=strategy,random_state =50)

X_blsmote , y_blsmote = blsmote.fit_resample(train_data_processed, train_y)
np.bincount(y_blsmote)

In [160]:
# ADASYN
from imblearn.over_sampling import ADASYN
strategy = {0:train_y_count[0]*5, 1:train_y_count[1], 2:train_y_count[2]*9}
adasyn = ADASYN(sampling_strategy = strategy,random_state=3)
X_ada , y_ada = adasyn.fit_resample(train_data_processed, train_y)

In [161]:
np.bincount(y_ada)

array([21351, 21240, 19445], dtype=int64)

#### Undersampling

In [162]:
from imblearn.under_sampling import TomekLinks #use TomekLinks and NearMiss

strategy = {1: round(21240*0.2), 0: 4134*5, 2: 2125*5}
random.seed(3)
undersample = TomekLinks(sampling_strategy= 'all')

X_tom , y_tom = undersample.fit_resample(X_ada,y_ada)

In [163]:
unique_tom = np.bincount(y_tom)
print(unique_tom)

[21345 21234 19445]


#NearMiss
from imblearn.under_sampling import NearMiss

strategy = {1: round(21240*0.3), 0: 4134, 2: 2125}
undersample_near = NearMiss(sampling_strategy=strategy)
X_near , y_near = undersample_near.fit_resample(train_data_processed, train_y)

unique_near = np.bincount(y_near)
print(unique_near)

#### One-sided Selection for Undersampling
from imblearn.under_sampling import OneSidedSelection

undersample_oss = OneSidedSelection(n_neighbors=1, n_seeds_S=1000)
X_oss , y_oss = undersample_oss.fit_resample(X_ada, y_ada)

np.bincount(y_oss)

#### SMOTETomek
from imblearn.combine import SMOTETomek
strategy = {1: round(21240*0.3), 0: 4134, 2: 2125}

smote_tomek = SMOTETomek(sampling_strategy = strategy, random_state=0)
X_smoteT , y_smoteT = smote_tomek.fit_resample(train_data_processed, train_y)
np.bincount(y_smoteT)

# Edited NN
from imblearn.under_sampling import EditedNearestNeighbours

undersample_enn = EditedNearestNeighbours(n_neighbors=3)
X_enn , y_enn = undersample_enn.fit_resample(X_smote, y_smote)

In [164]:
xg_train = xgb.DMatrix(X_tom, label=y_tom)
xg_valid = xgb.DMatrix(validation_data_processed, label=validation_y)

In [165]:
param = {}

# use softmax multi-class classification
param['objective'] = 'multi:softmax'
# scale weight of positive examples
param['eta'] = 0.257
param['max_depth'] = 1
param['nthread'] = -1
param['num_class'] = 3
param['max_delta_step'] = 1
#param['eval_metric'] = 'merror'
#param['scale_pos_weight'] = 0.5
#param['num_parallel_tree'] = 50

In [166]:
watchlist = [(xg_train, 'train'), (xg_valid, 'valid')]
num_round = 1000

In [167]:
bst = xgb.train(param, xg_train, num_round, watchlist, 
                callbacks=[xgb.callback.EvaluationMonitor(show_stdv=False),xgb.callback.EarlyStopping(8)])

[23:28:01] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softmax' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[0]	train-mlogloss:1.08343	valid-mlogloss:1.09681
[0]	train-mlogloss:1.08343	valid-mlogloss:1.09681
[1]	train-mlogloss:1.07318	valid-mlogloss:1.09815
[1]	train-mlogloss:1.07318	valid-mlogloss:1.09815
[2]	train-mlogloss:1.06577	valid-mlogloss:1.09983
[2]	train-mlogloss:1.06577	valid-mlogloss:1.09983
[3]	train-mlogloss:1.05994	valid-mlogloss:1.10148
[3]	train-mlogloss:1.05994	valid-mlogloss:1.10148
[4]	train-mlogloss:1.05457	valid-mlogloss:1.10289
[4]	train-mlogloss:1.05457	valid-mlogloss:1.10289
[5]	train-mlogloss:1.05022	valid-mlogloss:1.10507
[5]	train-mlogloss:1.05022	valid-mlogloss:1.10507
[6]	train-mlogloss:1.04631	valid-mlogloss:1.10868
[6]	train-mlogloss:1.04631	valid-mloglos

In [168]:
y_pred = bst.predict(xg_valid)

In [169]:
print(classification_report(validation_y, y_pred))

              precision    recall  f1-score   support

           0       0.28      0.63      0.39       741
           1       0.62      0.36      0.45      1610
           2       0.13      0.05      0.07       398

    accuracy                           0.39      2749
   macro avg       0.34      0.35      0.31      2749
weighted avg       0.46      0.39      0.38      2749



In [170]:
xg_test = xgb.DMatrix(test_data_processed)
y_pred_test = bst.predict(xg_test)

In [171]:
print(y_pred_test)

[0. 0. 1. ... 0. 1. 2.]


In [172]:
test_pred_df = pd.DataFrame({'Reservation-id': test_data_id, 'Reservation_Status':y_pred_test})
test_pred_df.head()

Reservation-id  Reservation_Status
0        62931593                 0.0
1        70586099                 0.0
2         4230648                 1.0
3        25192322                 0.0
4        80931528                 1.0

In [173]:
test_pred_df.to_csv('test_3.csv',',')

In [174]:
#np.bincount(validation_y)

array([ 741, 1610,  398], dtype=int64)

In [175]:
#len(y_pred_test)

4318